services:
  - type: web
    name: fincal-app
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 21.0.0
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        value: /sign-in
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        value: /sign-up
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
        value: /calculator
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
        value: /calculator
